### ISSUE TITLE
Mumsys Version for PHP 8.1 ?

### ISSUE THREAD

**Issue by aGiqs** [Mumsys/Library#1]
Hallo, Danke für die Library :-)  Ich finde es sehr nützlich :-) Gibt es schon die Pläne Mumsys-Library für PHP 8.1 zu aktualisieren?

**Comment by flobee** [comment]
Hi 'aGiqs'? yes... the plan is in the todo list. the dev tools must fit first to check upcomming problems for the next release. i think there ist something to do! would you like to help?

**Comment by aGiqs** [comment]
Why not?  Sure :-)

**Comment by flobee** [comment]
Your bug report:  is fixed in 2.1.1, but during the next hours/days 3.0.* will come including support 4 php8.1

this gives you more details: 
https://app.travis-ci.com/github/Mumsys/Library/branches
